language: python
python:
- '2.6'
- '2.7'
os:
- ubuntu
- centos
cache: pip
install: pip install -r requirements.txt
script: make check
deploy:
  provider: releases
  user: rymszmon
  api_key:
    secure: "aoU9WRbUBMkq4JiLpGLA2MiyH1sKdiD6e0isK99ubbpeRVb/u1kg24kwriqxzUOXgCRZ09v0CgJ5LvGV2L5X+636Dz2gGm99WK86F7llAbLFxJetY72vm4XVtJV+39p3SbgemmjpNy0aeC5Sm39FFMOfqlPNHUy6N9Urt2zbA7Nj9phOlEoXggC/vNEwxSI9tce/02I4tQKejaQG5lm9iMSmIrnMkXRlHMCknujr8uGvhElLbS05aGOKGL27cMf9PMCpQuKqCdd9FqDVxBHMLVcfrgFgkt8rNQWlBoLAykLyKykTASB5yRshiqqvKmRtSnQ35p+3DEIpUnCg4gvoXL1xUwx9NEC49NYO/S3ImqbOclRui7jYQ6xYHXeyDMdS1B+k6QjFlxxQH1791RnIkQKMd1J08bolwUqUlM1jZHyGTDacrqp4f1PHmXvDz8aZegPT1QC+yg/e/HZSRM9wN+4v6cMb5eKbdfi7BfcmG6R2c3CluKOgLth0DoCzxuXcBY75L0h4WiXVEW1u/lQf3YcrLYvDX+rCOdY37e0+/pj9PRPPrnC5pwecbR624F5HZ+VuuOfUuqfjzpe4EvaMAnh7mLsVkUWayohl7N/eFUftXDj2XwnKzIplQP6Vv8nPciJCHdcaQzGAk7C9MfqoxUuU4x0rxSenIt6LPS2TDX4="
  file: foo.py
  skip_cleanup: true
  on:
    repo: rymszmon/test-repo
    all_branches: true
    tags: false
